name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.14.4
  - numpy
  - pandas
  - bs4
  - nltk
  - tqdm
  - requests
  - pip
  - matplotlib
  - pip:
      - bm25s
      - ragas
      - vertexai
